//! Cherry-pick WPT reftest entry: runs arbitrary lists of tests
//! enumerated in crates/fulgur-wpt/expectations/lists/<name>.txt.
//!
//! Each `.txt` in that directory becomes one #[test] fn, generated by
//! build.rs at compile time. No edits here are required when adding a
//! new list — just drop a .txt file.

use fulgur_wpt::runner::run_list;
use std::path::PathBuf;

#[allow(dead_code)]
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

#[allow(dead_code)]
fn run(list_name: &str) {
    let expectations = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("expectations/lists")
        .join(format!("{list_name}.txt"));
    let outcome =
        run_list(&workspace_root(), list_name, &expectations, 96).expect("runner should not error");
    match outcome {
        Some(o) => eprintln!("list {list_name} report at {}", o.report_dir.display()),
        // `FULGUR_WPT_REQUIRED=1` is set only by the dedicated `wpt`
        // matrix job. Other CI cells and local dev without WPT fetched
        // must skip silently.
        None if std::env::var_os("FULGUR_WPT_REQUIRED").is_some() => {
            panic!(
                "wpt_list {list_name} prerequisites missing (run scripts/wpt/fetch.sh + install poppler-utils)"
            );
        }
        None => {}
    }
}

// Generated by build.rs: one `#[test] fn wpt_list_<stem>()` per file in
// expectations/lists/*.txt. The file may be empty if no lists exist yet.
include!(concat!(env!("OUT_DIR"), "/wpt_lists_generated.rs"));
