//! Generate one #[test] fn per file in expectations/lists/.
//!
//! The generated file is pulled in by tests/wpt_lists.rs via
//! `include!(concat!(env!("OUT_DIR"), "/wpt_lists_generated.rs"))`.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=expectations/lists");
    println!("cargo:rerun-if-changed=build.rs");

    let lists_dir = Path::new("expectations/lists");
    let mut stems: Vec<String> = Vec::new();
    if lists_dir.is_dir() {
        for entry in fs::read_dir(lists_dir).expect("read expectations/lists") {
            let entry = entry.expect("read entry");
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("txt") {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("utf-8 stem")
                .to_string();
            stems.push(stem);
        }
    }
    stems.sort();

    // Detect sanitize_ident collisions (e.g. `my-list` and `my_list` both map
    // to `my_list`) and fail the build with a clear message rather than
    // letting rustc flag a confusing duplicate-fn error.
    let mut ident_owner: BTreeMap<String, String> = BTreeMap::new();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n\n");
    for stem in &stems {
        let ident = sanitize_ident(stem);
        if let Some(prev) = ident_owner.insert(ident.clone(), stem.clone()) {
            panic!(
                "duplicate generated test identifier `wpt_list_{ident}` from list stems `{prev}.txt` and `{stem}.txt` — rename one of them"
            );
        }
        // Escape the raw stem before embedding it in the generated Rust
        // string literal. Filenames on POSIX may legally contain `"` and
        // `\`; without escaping, such a name would break compilation (or
        // be a code-injection vector).
        let escaped = stem.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!(
            "#[test] fn wpt_list_{ident}() {{ run(\"{escaped}\"); }}\n"
        ));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = Path::new(&out_dir).join("wpt_lists_generated.rs");
    fs::write(&out_path, out).expect("write generated tests");
}

/// Turn a filename stem into a valid Rust identifier: replace every
/// non-ASCII-alphanumeric char with '_'. Prepend '_' if the result is
/// empty or begins with a digit so it stays a valid Rust ident.
fn sanitize_ident(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 1);
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    match out.chars().next() {
        None => out.push('_'),
        Some(c) if c.is_ascii_digit() => out.insert(0, '_'),
        _ => {}
    }
    out
}
