//! Walk a directory of WPT reftests, run each through the harness, and
//! emit an `expectations/<subdir>.txt` with the observed PASS/FAIL/SKIP.
//!
//! Usage:
//!     cargo run -p fulgur-wpt --example seed -- \
//!         --subdir css-page \
//!         --wpt-root target/wpt \
//!         --out crates/fulgur-wpt/expectations/css-page.txt
//!
//! The expectations format matches `ExpectationFile::parse()`.

use anyhow::{Context, Result, bail};
use fulgur_wpt::expectations::Expectation;
use fulgur_wpt::fonts::load_fonts_dir;
use fulgur_wpt::harness::run_one;
use fulgur_wpt::reftest::collect_reftest_files;
use std::collections::BTreeMap;
use std::io::Write;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::path::{Path, PathBuf};
use std::time::Instant;

fn main() -> Result<()> {
    let mut subdir: Option<String> = None;
    let mut wpt_root: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;
    let mut args = std::env::args().skip(1);
    while let Some(flag) = args.next() {
        match flag.as_str() {
            "--subdir" => subdir = Some(args.next().context("--subdir needs value")?),
            "--wpt-root" => {
                wpt_root = Some(PathBuf::from(
                    args.next().context("--wpt-root needs value")?,
                ))
            }
            "--out" => out = Some(PathBuf::from(args.next().context("--out needs value")?)),
            other => bail!("unknown flag: {other}"),
        }
    }
    let subdir = subdir.context("--subdir required (e.g. css-page)")?;
    let wpt_root = wpt_root.context("--wpt-root required")?;
    let out = out.context("--out required")?;

    let dir = wpt_root.join("css").join(&subdir);
    anyhow::ensure!(dir.is_dir(), "not a directory: {}", dir.display());

    // Runner の execute_and_report と同条件で測定するために
    // target/wpt/fonts を同じく登録する（さもないと seed の PASS/FAIL
    // 基準が runner と drift する）。
    let fonts_bundle = load_fonts_dir(&wpt_root.join("fonts")).unwrap_or_else(|e| {
        eprintln!("warn: fonts loader failed: {e}; proceeding without bundled fonts");
        fulgur::asset::AssetBundle::new()
    });
    let fonts_arg = if fonts_bundle.fonts.is_empty() {
        None
    } else {
        Some(&fonts_bundle)
    };

    // Recursive walk via the shared helper — handles nested subdirectories
    // (tentative/, margin-boxes/, cssom/, ...) and the `-ref.tentative.html`
    // edge case that a suffix-only filter misses.
    let tests = collect_reftest_files(&dir).context("collect reftest files")?;

    let mut results: BTreeMap<String, (Expectation, Option<String>)> = BTreeMap::new();
    let total = tests.len();
    println!("Running {total} reftests in {}", dir.display());
    let start = Instant::now();

    for (i, test) in tests.iter().enumerate() {
        let rel = test
            .strip_prefix(&wpt_root)
            .unwrap_or(test)
            .to_string_lossy()
            .replace('\\', "/");
        let stem = test.file_stem().unwrap().to_string_lossy();
        let work = PathBuf::from("target/wpt-seed").join(&*stem).join("work");
        let diff = PathBuf::from("target/wpt-seed").join(&*stem).join("diff");
        let outcome = match catch_unwind(AssertUnwindSafe(|| {
            run_one(test, &work as &Path, &diff as &Path, 96, fonts_arg)
        })) {
            Ok(Ok(o)) => (o.observed, o.reason),
            Ok(Err(e)) => (Expectation::Fail, Some(format!("harness error: {e}"))),
            Err(p) => {
                let msg = if let Some(s) = p.downcast_ref::<&str>() {
                    (*s).to_string()
                } else if let Some(s) = p.downcast_ref::<String>() {
                    s.clone()
                } else {
                    "unknown panic".to_string()
                };
                (Expectation::Fail, Some(format!("harness panic: {msg}")))
            }
        };
        let status_str = match outcome.0 {
            Expectation::Pass => "PASS",
            Expectation::Fail => "FAIL",
            Expectation::Skip => "SKIP",
        };
        println!("[{:>3}/{}] {status_str}  {rel}", i + 1, total);
        results.insert(rel, outcome);
    }

    let elapsed = start.elapsed();
    let mut pass = 0u32;
    let mut fail = 0u32;
    let mut skip = 0u32;
    for (e, _) in results.values() {
        match e {
            Expectation::Pass => pass += 1,
            Expectation::Fail => fail += 1,
            Expectation::Skip => skip += 1,
        }
    }

    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut f = std::fs::File::create(&out)?;
    writeln!(
        f,
        "# Auto-generated by `cargo run -p fulgur-wpt --example seed`."
    )?;
    writeln!(
        f,
        "# Summary: {pass} PASS, {fail} FAIL, {skip} SKIP (total {total})."
    )?;
    writeln!(
        f,
        "# Promote to PASS by editing this file in a PR after verifying the harness output."
    )?;
    writeln!(f)?;
    for (rel, (status, reason)) in &results {
        let status_str = match status {
            Expectation::Pass => "PASS",
            Expectation::Fail => "FAIL",
            Expectation::Skip => "SKIP",
        };
        match reason {
            Some(r) => {
                let r1 = r.replace(['\n', '\r'], " ");
                writeln!(f, "{status_str:4}  {rel}  # {r1}")?;
            }
            None => writeln!(f, "{status_str:4}  {rel}")?,
        }
    }

    println!(
        "\nSeeded {} entries in {:.1}s: {pass} PASS, {fail} FAIL, {skip} SKIP",
        results.len(),
        elapsed.as_secs_f64()
    );
    println!("Wrote {}", out.display());
    Ok(())
}
